# General
targets: "targets/udp/53/2025-04-29_00-33-19" # Use e.g. "tcp/80/<timestamp>" or just "latest" to automatically get your most recent target file for your config
protocol: "udp" # TODO Use a list like ["icmp", "tcp"] to enable inter-protocol IPID measurements
record_traffic: false

# TCP
tcp_dst_port: 80
tcp_request_flags: "S" # S=SYN A=ACK R=RST, e.g. "SA" for SYN-ACK
tcp_src_port_offset: 22570

# UDP
udp_dst_port: 53
udp_src_port_offset: 32570

# B2B Probing
b2b_request_count: 10
b2b_request_interval: "10ms"
b2b_retry_count: 0

# SEQ Probing
seq_request_count: 10
seq_retry_count: 2

# Other
iface_a:
  name: "eth0"
  ip: "141.76.94.12"
iface_b:
  name: "eth1"
  ip: "141.76.94.15"
max_rtt: "2s"
send_bandwidth: "30M"
default_send_ip_ids: [0] # Sends [0,0,0,...]
detect_reflected_ip_ids: false
reflection_send_ip_ids: [3717,3718,3719] # Sequence must not match with any known pattern
is_linux_low_ram: true # Enables disk-based calculations on low-RAM Linux systems

# Dataframe column names
ip_col_name: "IP"
ts_ip_col_name: "TS_IP"
us_ip_col_name: "US_IP"
os_col_name: "OS"
ts_os_col_name: "TS_OS"

ip_id_seq_col_name: "IP_ID_SEQUENCE"
send_ts_seq_col_name: "SEND_TS_SEQUENCE"
received_ts_seq_col_name: "RECEIVED_TS_SEQUENCE"
check_seq_col_name: "CHECK_SEQUENCE"

ip_id_pattern_col_name: "IP_ID_PATTERN"
avg_rtt_col_name: "AVG_RTT"
std_rtt_col_name: "STD_RTT"
asn_col_name: "ASN"

as_org_col_name: "AS_ORGANIZATION"
country_col_name: "COUNTRY"
continent_col_name: "CONTINENT"
