# General
targets: "targets/icmp/2025-05-24_22-02-30" # Use e.g. "targets/tcp/80/<timestamp>" or just "latest" to automatically get your most recent target file for your config
protocol: "icmp" # TODO Use a list like ["icmp", "tcp"] to enable inter-protocol measurements
record_traffic: False

# TCP
tcp_dst_port: 80
tcp_request_flags: "S" # S=SYN, A=ACK, R=RST, e.g. SA=SYN-ACK
tcp_src_port_offset: 22570

# UDP
udp_dst_port: 53
udp_src_port_offset: 32570

# B2B Probing
b2b_request_count: 10
b2b_request_interval: "10ms"
b2b_retry_count: 0

# SEQ Probing
seq_request_count: 10
seq_retry_count: 0

# MASS Probing
mass_request_count: 100
mass_request_interval: "70ms"
mass_reply_portion_threshold: 0.8

# Probing
iface_a:
  name: "eth0"
  ip: "141.76.94.12"
iface_b:
  name: "eth1"
  ip: "141.76.94.15"
min_rtt: "2s"
default_send_ip_ids: [ 0 ] # Sends [0,0,0,...]
detect_reflected_ip_ids: True
reflection_send_ip_ids: [ 18933,18933,3717,3718,3719 ] # Sequence with fixed arbitrary values

# Hitlist
zmap_bandwidth: "30M" # Bandwidth for zmap scans (K=Kbps, M=Mbps, G=Gbps)

# Filenames # TODO Use this as reference consistently
targets_ip_fn: "targets.csv.zst"
targets_os_fn: "targets_os.csv.zst"

probing_fn: "probing.csv.zst"
eval_fn: "eval.csv.zst"

# Dataframe column names # TODO Use this as reference consistently
ip_col_name: "IP"
ts_ip_col_name: "TS_IP"
us_ip_col_name: "US_IP"

os_col_name: "OS"
ts_os_col_name: "TS_OS"
us_os_col_name: "US_OS"
os_data_col_name: "OS_DATA"

ip_id_seq_col_name: "IP_ID_SEQUENCE"
sent_ts_seq_col_name: "SENT_TS_SEQUENCE"
received_ts_seq_col_name: "RECEIVED_TS_SEQUENCE"

ip_id_pattern_col_name: "IP_ID_PATTERN"
avg_rtt_col_name: "AVG_RTT"
std_rtt_col_name: "STD_RTT"
asn_col_name: "ASN"
