# General
targets: "latest" # Use e.g. "tcp/80/<timestamp>" or just "latest" to automatically get your most recent target file for your config
protocol: ["icmp"]
record_traffic: false

# TCP
tcp_dst_port: 80
tcp_request_flags: "S"
tcp_src_port_offset: 22570

# UDP
udp_dst_port: 53
udp_src_port_offset: 32570

# B2B Probing
b2b_request_count: 20
b2b_request_interval: "10ms"

# SEQ Probing
seq_request_count: 20

# Other
iface_a:
  name: "eth0"
  ip: "141.76.94.12"
iface_b:
  name: "eth1"
  ip: "141.76.94.15"
max_rtt: "2s"
send_mbps: 100
default_send_ip_ids: [0] # Sends [0,0,0,...]
detect_reflected_ip_ids: false
reflection_send_ip_ids: [3717,3718,3719] # Sequence must not match with any known pattern
